### ISSUE TITLE
submission to CRAN?

### ISSUE THREAD

**Issue by nick-youngblut** [JCVenterInstitute/GGRaSP#1]
The `GGRaSP` package looks like a very useful tool for microbial genomics. As far as I can tell, it's not available from CRAN. Just hosting the package on GitHub can make it harder to install and maintain specific versions via packrat, conda, etc. Submitting the package to CRAN can help users actually use `GGRaSP` in a reproducible software environment, and there's other benefits to hosting on CRAN (see [Hadley Wickham's R package book](http://r-pkgs.had.co.nz/release.html)). 

Are you planning (or currently working on) submitting `GGRaSP` to CRAN?

**Comment by thclarke** [comment]
Thank you- this is an excellent idea. We have begun the submission process to CRAN. We still recommend using the GGRaSP github site for extra features, such as the command line R script (ggrasp.R).

**Comment by nick-youngblut** [comment]
Thanks for working on the CRAN submission! It shouldn't be much work if your package is formatted properly, which it appears to be. My research group uses conda to manage (almost) all software, so I'm planning on creating a bioconda recipe for `GGRaSP`, which can work with a GitHub release tag, but it's better to use a CRAN url.

**Comment by thclarke** [comment]
GGRaSP is now available on CRAN (https://cran.r-project.org/web/packages/ggrasp/index.html). Thanks for the suggestion.
